name: Branch Name Check

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  check:
    uses: AtticAIInc/.github/.github/workflows/branch-name-check.yml@main
    with:
      enforcement-mode: soft
